# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'deposit_calc.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(825, 900)
        MainWindow.setMinimumSize(QSize(825, 900))
        MainWindow.setMaximumSize(QSize(825, 900))
        MainWindow.setInputMethodHints(Qt.ImhNone)
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextOnly)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tax_line_edit_2 = QLineEdit(self.centralwidget)
        self.tax_line_edit_2.setObjectName(u"tax_line_edit_2")
        self.tax_line_edit_2.setGeometry(QRect(30, 650, 491, 41))
        font = QFont()
        font.setPointSize(18)
        self.tax_line_edit_2.setFont(font)
        self.tax_line_edit_2.setReadOnly(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(570, 80, 241, 51))
        self.label_2.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(540, 710, 261, 61))
        self.label_6.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(490, 190, 321, 61))
        self.label_3.setFont(font)
        self.time_line_edit = QLineEdit(self.centralwidget)
        self.time_line_edit.setObjectName(u"time_line_edit")
        self.time_line_edit.setGeometry(QRect(30, 200, 431, 41))
        self.time_line_edit.setFont(font)
        self.rate_line_edit = QLineEdit(self.centralwidget)
        self.rate_line_edit.setObjectName(u"rate_line_edit")
        self.rate_line_edit.setGeometry(QRect(30, 80, 431, 41))
        self.rate_line_edit.setFont(font)
        self.make_deposit_button = QPushButton(self.centralwidget)
        self.make_deposit_button.setObjectName(u"make_deposit_button")
        self.make_deposit_button.setGeometry(QRect(150, 790, 511, 61))
        font1 = QFont()
        font1.setPointSize(23)
        self.make_deposit_button.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(540, 580, 261, 41))
        self.label_4.setFont(font)
        self.payment_line_edit = QLineEdit(self.centralwidget)
        self.payment_line_edit.setObjectName(u"payment_line_edit")
        self.payment_line_edit.setGeometry(QRect(30, 580, 491, 41))
        self.payment_line_edit.setFont(font)
        self.payment_line_edit.setReadOnly(True)
        self.sum_deposit_line_edit = QLineEdit(self.centralwidget)
        self.sum_deposit_line_edit.setObjectName(u"sum_deposit_line_edit")
        self.sum_deposit_line_edit.setGeometry(QRect(30, 20, 431, 41))
        self.sum_deposit_line_edit.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(670, 640, 141, 61))
        self.label_5.setFont(font)
        self.total_line_edit = QLineEdit(self.centralwidget)
        self.total_line_edit.setObjectName(u"total_line_edit")
        self.total_line_edit.setGeometry(QRect(30, 720, 491, 41))
        self.total_line_edit.setFont(font)
        self.total_line_edit.setReadOnly(True)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(620, 10, 191, 61))
        self.label.setFont(font)
        self.tax_line_edit = QLineEdit(self.centralwidget)
        self.tax_line_edit.setObjectName(u"tax_line_edit")
        self.tax_line_edit.setGeometry(QRect(30, 140, 431, 41))
        self.tax_line_edit.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(720, 130, 91, 61))
        self.label_7.setFont(font)
        self.capitalization_checkbox = QCheckBox(self.centralwidget)
        self.capitalization_checkbox.setObjectName(u"capitalization_checkbox")
        self.capitalization_checkbox.setGeometry(QRect(540, 480, 261, 23))
        self.capitalization_checkbox.setFont(font)
        self.replenishment_line_edit = QLineEdit(self.centralwidget)
        self.replenishment_line_edit.setObjectName(u"replenishment_line_edit")
        self.replenishment_line_edit.setGeometry(QRect(30, 260, 431, 41))
        self.replenishment_line_edit.setFont(font)
        self.withdrawal_line_edit = QLineEdit(self.centralwidget)
        self.withdrawal_line_edit.setObjectName(u"withdrawal_line_edit")
        self.withdrawal_line_edit.setGeometry(QRect(30, 360, 431, 41))
        self.withdrawal_line_edit.setFont(font)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(630, 250, 171, 61))
        self.label_9.setFont(font)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(670, 350, 131, 61))
        self.label_10.setFont(font)
        self.replenishment_combobox = QComboBox(self.centralwidget)
        self.replenishment_combobox.addItem("")
        self.replenishment_combobox.setObjectName(u"replenishment_combobox")
        self.replenishment_combobox.setGeometry(QRect(30, 310, 431, 31))
        font2 = QFont()
        font2.setPointSize(16)
        self.replenishment_combobox.setFont(font2)
        self.withdrawal_combobox = QComboBox(self.centralwidget)
        self.withdrawal_combobox.addItem("")
        self.withdrawal_combobox.setObjectName(u"withdrawal_combobox")
        self.withdrawal_combobox.setGeometry(QRect(30, 410, 431, 31))
        self.withdrawal_combobox.setFont(font2)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 460, 211, 61))
        self.label_11.setFont(font)
        self.frequency_combobox = QComboBox(self.centralwidget)
        self.frequency_combobox.setObjectName(u"frequency_combobox")
        self.frequency_combobox.setGeometry(QRect(230, 480, 231, 31))
        self.frequency_combobox.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 825, 22))
        self.menuDeposit_OOO_Bank = QMenu(self.menubar)
        self.menuDeposit_OOO_Bank.setObjectName(u"menuDeposit_OOO_Bank")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuDeposit_OOO_Bank.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.tax_line_edit_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Percent % rate, yearly", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Final amoint on deposit", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Time/placement period(days)", None))
        self.time_line_edit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.rate_line_edit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.make_deposit_button.setText(QCoreApplication.translate("MainWindow", u"Make a deposit", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Interest charges(% got)", None))
        self.payment_line_edit.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.sum_deposit_line_edit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Tax amount", None))
        self.total_line_edit.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sum of a deposit", None))
        self.tax_line_edit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Tax rate", None))
        self.capitalization_checkbox.setText(QCoreApplication.translate("MainWindow", u"Interest capitalization", None))
        self.replenishment_line_edit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.withdrawal_line_edit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Replenishment", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Withdrawal", None))
        self.replenishment_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))

        self.withdrawal_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))

        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Pay/t frequency", None))
        self.menuDeposit_OOO_Bank.setTitle(QCoreApplication.translate("MainWindow", u"Deposit OOO Bank", None))
    # retranslateUi

