# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.small_button = QPushButton(self.centralwidget)
        self.small_button.setObjectName(u"small_button")
        self.small_button.setGeometry(QRect(650, 190, 101, 51))
        font = QFont()
        font.setPointSize(20)
        self.small_button.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 40, 61, 41))
        font1 = QFont()
        font1.setPointSize(25)
        self.label.setFont(font1)
        self.sin_button = QPushButton(self.centralwidget)
        self.sin_button.setObjectName(u"sin_button")
        self.sin_button.setGeometry(QRect(40, 190, 101, 51))
        font2 = QFont()
        font2.setPointSize(16)
        self.sin_button.setFont(font2)
        self.cos_button = QPushButton(self.centralwidget)
        self.cos_button.setObjectName(u"cos_button")
        self.cos_button.setGeometry(QRect(160, 190, 101, 51))
        self.cos_button.setFont(font2)
        self.tan_button = QPushButton(self.centralwidget)
        self.tan_button.setObjectName(u"tan_button")
        self.tan_button.setGeometry(QRect(280, 190, 101, 51))
        self.tan_button.setFont(font2)
        self.atan_button = QPushButton(self.centralwidget)
        self.atan_button.setObjectName(u"atan_button")
        self.atan_button.setGeometry(QRect(40, 250, 101, 51))
        self.atan_button.setFont(font2)
        self.asin_button = QPushButton(self.centralwidget)
        self.asin_button.setObjectName(u"asin_button")
        self.asin_button.setGeometry(QRect(520, 190, 101, 51))
        self.asin_button.setFont(font2)
        self.acos_button = QPushButton(self.centralwidget)
        self.acos_button.setObjectName(u"acos_button")
        self.acos_button.setGeometry(QRect(400, 190, 101, 51))
        self.acos_button.setFont(font2)
        self.sqrt_button = QPushButton(self.centralwidget)
        self.sqrt_button.setObjectName(u"sqrt_button")
        self.sqrt_button.setGeometry(QRect(160, 250, 101, 51))
        self.sqrt_button.setFont(font2)
        self.ln_button = QPushButton(self.centralwidget)
        self.ln_button.setObjectName(u"ln_button")
        self.ln_button.setGeometry(QRect(280, 250, 101, 51))
        self.ln_button.setFont(font2)
        self.log_button = QPushButton(self.centralwidget)
        self.log_button.setObjectName(u"log_button")
        self.log_button.setGeometry(QRect(400, 250, 101, 51))
        self.log_button.setFont(font2)
        self.line_input_field = QLineEdit(self.centralwidget)
        self.line_input_field.setObjectName(u"line_input_field")
        self.line_input_field.setGeometry(QRect(40, 100, 711, 61))
        self.line_input_field.setFont(font)
        self.x_input_field = QLineEdit(self.centralwidget)
        self.x_input_field.setObjectName(u"x_input_field")
        self.x_input_field.setGeometry(QRect(110, 40, 171, 41))
        self.x_input_field.setFont(font1)
        self.clear_button = QPushButton(self.centralwidget)
        self.clear_button.setObjectName(u"clear_button")
        self.clear_button.setGeometry(QRect(590, 40, 161, 41))
        self.clear_button.setFont(font2)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 320, 121, 41))
        self.label_2.setFont(font)
        self.mod_button = QPushButton(self.centralwidget)
        self.mod_button.setObjectName(u"mod_button")
        self.mod_button.setGeometry(QRect(520, 250, 101, 51))
        self.mod_button.setFont(font2)
        self.plot_button = QPushButton(self.centralwidget)
        self.plot_button.setObjectName(u"plot_button")
        self.plot_button.setGeometry(QRect(480, 420, 271, 111))
        self.plot_button.setFont(font)
        self.credit_button = QPushButton(self.centralwidget)
        self.credit_button.setObjectName(u"credit_button")
        self.credit_button.setGeometry(QRect(40, 390, 201, 71))
        self.credit_button.setFont(font)
        self.output_field = QLineEdit(self.centralwidget)
        self.output_field.setObjectName(u"output_field")
        self.output_field.setGeometry(QRect(170, 320, 581, 41))
        self.output_field.setFont(font)
        self.deposit_button = QPushButton(self.centralwidget)
        self.deposit_button.setObjectName(u"deposit_button")
        self.deposit_button.setGeometry(QRect(40, 500, 201, 71))
        self.deposit_button.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.small_button.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"x = ", None))
        self.sin_button.setText(QCoreApplication.translate("MainWindow", u"Sin", None))
        self.cos_button.setText(QCoreApplication.translate("MainWindow", u"Cos", None))
        self.tan_button.setText(QCoreApplication.translate("MainWindow", u"Tan", None))
        self.atan_button.setText(QCoreApplication.translate("MainWindow", u"Atan", None))
        self.asin_button.setText(QCoreApplication.translate("MainWindow", u"Asin", None))
        self.acos_button.setText(QCoreApplication.translate("MainWindow", u"Acos", None))
        self.sqrt_button.setText(QCoreApplication.translate("MainWindow", u"Sqrt", None))
        self.ln_button.setText(QCoreApplication.translate("MainWindow", u"Ln", None))
        self.log_button.setText(QCoreApplication.translate("MainWindow", u"Log", None))
        self.line_input_field.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.x_input_field.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.clear_button.setText(QCoreApplication.translate("MainWindow", u"Clear input", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Result =", None))
        self.mod_button.setText(QCoreApplication.translate("MainWindow", u"Mod", None))
        self.plot_button.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.credit_button.setText(QCoreApplication.translate("MainWindow", u"Credit", None))
        self.output_field.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.deposit_button.setText(QCoreApplication.translate("MainWindow", u"Deposit", None))
    # retranslateUi

